#include <gmock/gmock.h>
/*
 * DO NOT EDIT THIS FILE
 *
 * Create a separate test file instead.
 *
 * A good convention is to create one "*.test.cpp"
 * file for each tested class
 *
 */
int main(int argc, char**argv) {
    ::testing::InitGoogleMock(&argc,argv);
    return RUN_ALL_TESTS();
} 